#!/bin/sh

#
# fluxbox startup script
#

# Set some variables.
export QT_QPA_PLATFORMTHEME=gtk2
export G_SLICE=always-malloc
export PATH=$PATH:~/.local/bin

# Applications you want to run with fluxbox.
xsetroot -solid black &
nitrogen --restore &
redshift -c ~/.config/redshift/redshift.conf &
xautolock -time 15 -locker "i3lock-fancy-dualmonitor" &
(sleep 1 && picom-next --config ~/.config/picom.conf --experimental-backends) &
(sleep 2 && tint2 -c ~/.config/tint2/tint2rc-left) &
(sleep 2 && tint2 -c ~/.config/tint2/tint2rc-right) &

# And some other shit I want in the background...
touch ~/.cache/run-cowsay-login
(sleep 3 && udiskie) &
(sleep 2 && hydroxide serve) &
(sleep 4 && ~/.local/share/go/bin/mpdfavd -config-file ~/.config/mpdfav.json) &
(sleep 3 && ~/src/scripts/getweather.sh) &
(sleep 3 && ~/src/scripts/sync-playcounts.sh) &

# And last but not least we start fluxbox.
exec fluxbox -no-toolbar
